# Generated by Django 4.0.4 on 2022-06-25 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_created=True, auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('name', models.CharField(blank=True, max_length=15, verbose_name='نام وام')),
                ('m_vam', models.IntegerField(verbose_name='مبلغ وام')),
                ('m_ghest', models.IntegerField(verbose_name='مبلغ قسط')),
                ('t_gest', models.IntegerField(verbose_name='تعداد قسط')),
                ('choice', models.CharField(choices=[('پرداخت شده', 'پرداخت شده'), ('پرداخت نشده', 'پرداخت نشده'), ('در حال پرداخت', 'در حال پرداخت'), ('در انتظار پرداخت', 'در انتظار پرداخت')], default='در انتظار پرداخت', max_length=30, verbose_name='وضعیت')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مدیر')),
            ],
            options={
                'verbose_name': 'وام ها',
            },
        ),
        migrations.CreateModel(
            name='Sandogh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='زمان ایجاد صندوق')),
                ('name', models.CharField(max_length=60, verbose_name='نام صندوق')),
                ('saham', models.IntegerField(verbose_name='تعداد سهام')),
                ('m_saham', models.IntegerField(verbose_name='مبلغ هر سهم ')),
                ('m_sandogh', models.IntegerField(verbose_name='موجودی صندوق ')),
                ('shomare_hesab', models.IntegerField(verbose_name='شماره حساب')),
                ('rolls', models.TextField(blank=True, max_length=10000, verbose_name='توضیحات و قوانین')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد صندوق')),
                ('sandogh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مدیر')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_created=True, auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('status', models.CharField(choices=[('active', 'وام گرفته'), ('inactive', 'وام نگرفته')], default='inactive', max_length=10, verbose_name='وضعیت')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('family', models.CharField(blank=True, max_length=100, verbose_name='نام خانوادگی')),
                ('phone', models.IntegerField(blank=True, verbose_name='شماره تلفن')),
                ('t_saham', models.IntegerField(verbose_name='تعداد سهام')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مدیر')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.sandogh', verbose_name='صندوق')),
            ],
            options={
                'verbose_name': 'اعضا',
            },
        ),
        migrations.CreateModel(
            name='Lottory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_created=True, auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('family', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.loan', verbose_name='نام وام')),
            ],
            options={
                'verbose_name': 'برنده ها',
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='sandogh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.sandogh', verbose_name='صندوق'),
        ),
    ]
