# Generated by Django 4.0.4 on 2022-06-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('وام گرفته', 'وام گرفته'), ('وام نگرفته', 'وام نگرفته')], default='وام نگرفته', max_length=10, verbose_name='وضعیت'),
        ),
    ]
